### PR TITLE
Fix: Old Chalk.JS deprecated method (fixes #5716)

### LINKED ISSUE #5716: v2.5.3 not working with chalk v1.1.2
**What version of ESLint are you using?**
v2.5.3
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
{
  "extends": "name",
  "rules": {
    "no-useless-call": 1,
    "comma-dangle": 2
  }
}

**What did you do? Please include the actual source code causing the issue.**
npm install
**What did you expect to happen?**
working
**What actually happened? Please include the actual, raw output from ESLint.**
.../node_modules/gulp-eslint/node_modules/eslint/lib/formatters/stylish.js:71
                    return chalk.stripColor(str).length;
                                 ^

TypeError: chalk.stripColor is not a function
    at table.stringLength (.../node_modules/gulp-eslint/node_modules/eslint/lib/formatters/stylish.js:71:34)
    at .../node_modules/text-table/index.js:33:21
    at Array.forEach (native)
    at forEach (.../node_modules/text-table/index.js:73:31)
    at .../node_modules/text-table/index.js:32:9
    at Array.reduce (native)
    at reduce (.../node_modules/text-table/index.js:63:30)
    at module.exports (.../node_modules/text-table/index.js:31:17)
    at .../node_modules/gulp-eslint/node_modules/eslint/lib/formatters/stylish.js:46:19
    at Array.forEach (native)

Thank you

### PR DESCRIPTION
**Pull request by morrissinger**
Picks up where https://github.com/eslint/eslint/pull/5731 left off.

### CODE REVIEW

**Comment by sindresorhus** [comment]
This PR is not needed. `^1.0.0` will match `1.1.3` just fine.

**Comment by morrissinger** [comment]
@sindresorhus, the problem with that thinking is that if I have chalk@1.1.2 from another dependency in the same project, then eslint will fail and there is no way to fix it short of a fork.

**Comment by morrissinger** [comment]
At least with npm 3...

**Comment by nzakas** [comment]
Lgtm. Thanks @morrissinger

**Comment by nzakas** [comment]
Oops, can you change the commit summary to begin with "Upgrade:" instead of "Fix:"? You can just amend the commit message as described here: http://eslint.org/docs/developer-guide/contributing/pull-requests#updating-the-commit-message

**Comment by morrissinger** [comment]
Thanks, @nzakas. I fixed the commit summary per your request. The Travis and Appveyor checks have passed. So, it looks like the rest is on your team to merge when ready.

**Comment by ilyavolodin** [comment]
Thanks for PR. LGTM
