### PR TITLE
fix: add missing CodePath and CodePathSegment types

### PR DESCRIPTION
**Pull request by Pixel998**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### AI acknowledgment

- [x] I did _not_ use AI to generate this PR.
- [ ] (If the above is not checked) I have reviewed the AI-generated content before submitting.

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment (`npx eslint --env-info`):**

- **Node version: v24.15.0**
- **npm version: v11.12.1**
- **Local ESLint version: v10.3.0**
- **Global ESLint version:**
- **Operating System:**

**What parser are you using (place an "X" next to just one item)?**

[x] `Default (Espree)`
[ ] `@typescript-eslint/parser`
[ ] `@babel/eslint-parser`
[ ] `vue-eslint-parser`
[ ] `@angular-eslint/template-parser`
[ ] `Other`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
onCodePathEnd(codePath) {
    codePath.traverseSegments((segment, controller) => {
      segment.allNextSegments;
      segment.allPrevSegments;
    });
},
```

**What did you expect to happen?**

I expected the TypeScript declarations to match the existing runtime code path analysis API, so that `CodePath#traverseSegments()` and `CodePathSegment#allNextSegments` / `allPrevSegments` could be used without type errors.

**What actually happened? Please include the actual, raw output from ESLint.**

TypeScript reported errors:

```
Property 'traverseSegments' does not exist on type 'CodePath'.
...
```

#### What changes did you make? (Give an overview)

- Updated the `Rule.CodePath` and `Rule.CodePathSegment` types to include runtime members that were missing from the TypeScript declarations.
- Added type coverage for these members.
- Updated the code path analysis documentation to describe `traverseSegments()` and the `allNextSegments` / `allPrevSegments` properties.

### CODE REVIEW

**Review by DMartens — APPROVED** [review]
Changes LGTM, thanks. Leaving open for second review as maybe this is not meant to be part of the public API. I could not find information regarding this in prior issues / PRs.

**Comment by fasttime** [comment]
I think it's fine to add documentation here. `allNextSegments` and `allPrevSegments` have existed since the beginnings of code path analysis and are already used in many projects. `CodePath#traverseSegments` was introduced in #5278 for use by the `no-this-before-super` rule, so it's not internal to the core. I guess this is a case where the documentation hasn't always been updated consistently.

**Review by fasttime — APPROVED** [review]
LGTM, thanks!
