### ISSUE TITLE
ESLint Crashed - Cannot find module 'del'

### ISSUE THREAD

**Issue by ndaidong** [eslint/eslint#4036]
Hi there,

I just got the following error after updating eslint to v1.5.1:

```
Error: Cannot find module 'del'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint/node_modules/file-entry-cache/node_modules/flat-cache/cache.js:5:11)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.create (/usr/local/lib/node_modules/eslint/node_modules/file-entry-cache/cache.js:12:21)
    at new CLIEngine (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:363:38)
    at Object.provider.lint (/home/ndaidong/.atom/packages/linter-eslint/lib/linter-eslint.coffee:83:24)
    at Promise.then._this.emitter.emit.linter (/home/ndaidong/.atom/packages/linter/lib/linter-registry.coffee:59:22)
    at LinterRegistry.triggerLinter (/home/ndaidong/.atom/packages/linter/lib/linter-registry.coffee:58:16)
    at /home/ndaidong/.atom/packages/linter/lib/linter-registry.coffee:52:17
    at Array.map (native)
    at /home/ndaidong/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

I'm coding with ATOM v1.0.9, environment: node.js v4.1.1, npm v3.3.4, Linux Mint 17.2

Screenshots:

Error alert in ATOM: http://i.imgur.com/An1CRcK.png
Error message in Sublime: http://i.imgur.com/KUrsdn6.png

Please let me know how to detect what is the cause of this issue?

Thank for any help.

**Comment by eslintbot** [comment]
Thanks for the issue! If you're reporting a bug, please be sure to include:

1. The version of ESLint you are using (run `eslint -v`)
2. What you did (the source code and ESLint configuration)
3. The actual ESLint output complete with numbers
4. What you expected to happen instead

Requesting a new rule? Please see [Proposing a New Rule](http://eslint.org/docs/developer-guide/contributing/new-rules) for instructions.

**Comment by ndaidong** [comment]
Fortunately, I have updated to v1.6.0 and the error no longer occur. So I would like to close this issue, please focus on other tasks.
