### ISSUE TITLE
"TypeError: ruleMapper is not a function" after upgrading to 5.16.0

### ISSUE THREAD

**Issue by tomhoogenboom** [eslint/eslint#11578]
**Tell us about your environment**

* **ESLint Version:**
v5.16.0
* **Node Version:**
v10.15.3
* **npm Version:**
v6.4.1
**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "plugins": [
    "react-hooks"
  ],
  "extends": [
    "standard",
    "standard-react"
  ],
  "rules": {
    "jsx-quotes": [
      "error",
      "prefer-double"
    ],
    "react/jsx-indent": [
      "error",
      2
    ],
    "react/jsx-indent-props": [
      "error",
      2
    ],
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "lines-between-class-members": 2,
    "no-useless-escape": 2,
    "object-curly-spacing": [
      "error",
      "always"
    ],
    "react-hooks/rules-of-hooks": "error"
  },
  "env": {
    "jest": true
  },
  "globals": {
    "__": true,
    "File": true,
    "FileList": true,
    "atob": true,
    "API_URL": true
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
Upgraded from eslint 5.12.0 to 5.16.0

```js
export default {
  RAFFLE_TICKET: 'raffleticket',
  CASHBACK: 'cashback',
  GIFTVOUCHER: 'giftvoucher'
}
```

```bash
eslint 'src/**/*.js'
```

**What did you expect to happen?**
Nothing

**What actually happened? Please include the actual, raw output from ESLint.**
Gave the following error:
```
TypeError: ruleMapper is not a function

TypeError: ruleMapper is not a function
    at Object.keys.forEach.id (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config/config-validator.js:176:29)
    at Array.forEach (<anonymous>)
    at validateRules (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config/config-validator.js:175:30)
    at Object.validate (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config/config-validator.js:262:5)
    at loadFromDisk (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config/config-file.js:544:19)
    at Object.load (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/tomhoogenboom/projects/tessa-webpromotions/node_modules/eslint/lib/config.js:342:29)
Process finished with exit code -1
```

**Comment by mysticatea** [comment]
Thank you for this report.

However, I couldn't reproduce it.
Would you re-install ESLint and related packages?
I'm suspecting that it's an installation problem.

**Comment by tomhoogenboom** [comment]
Hmmm, I though I already did that but now after deleting and installing again it did indeed work. So I guess it can be closed. Sorry to waste your time.

**Comment by lkiarest** [comment]
I have the same problem in VS Code. And have to downgrade to 5.15.0.

**Comment by mysticatea** [comment]
> I have the same problem in VS Code. And have to downgrade to 5.15.0.

Please ensure to restart VS Code (or run "Reload Window" command) after upgrading.
