### ISSUE TITLE
6.0.1: Error: Cannot find module 'eslint/lib/formatters/stylish'

### ISSUE THREAD

**Issue by rwieruch** [eslint/eslint#11910]
I run into the following error when I try to build my project which uses ESLint 6.0.1. after upgrading it:

```
ERROR in ./src/index.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint/lib/formatters/stylish'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/Users/me/Developer/Repos/use-custom-element/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.module.exports (/Users/me/Developer/Repos/use-custom-element/node_modules/eslint-loader/index.js:199:26)
```

Just yesterday I updated ESLint. I can confirm that it still works with version **5.16.0**.

This minimal boilerplate project runs https://codesandbox.io/s/github/rwieruch/advanced-react-webpack-babel-setup But will fail with ESLint version 6.0.1.

Related: https://github.com/vuejs/eslint-plugin-vue/issues/916

**Comment by mysticatea** [comment]
Thank you for your report.

However, this is a problem in `eslint-loader` package and we are not the maintainer of that package. Please report to `eslint-loader`'s repo.

**Comment by rupamkhaitan** [comment]
In the eslint-loader README file you can see

#### `formatter` (default: eslint stylish formatter)

Loader accepts a function that will have one argument: an array of eslint messages (object).
The function must return the output as a string.
You can use official eslint formatters.

```js
module.exports = {
  entry: "...",
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "eslint-loader",
        options: {
          // several examples !

          // default value
          formatter: require("eslint/lib/formatters/stylish"),

          // community formatter
          formatter: require("eslint-friendly-formatter"),

          // custom formatter
          formatter: function(results) {
            // `results` format is available here
            // http://eslint.org/docs/developer-guide/nodejs-api.html#executeonfiles()

            // you should return a string
            // DO NOT USE console.*() directly !
            return "OUTPUT";
          }
        }
      }
    ]
  }
};
```

**Comment by rupamkhaitan** [comment]
In the latest build of eslint 6.0.1 they moved the file path to below
./lib/cli-engine/formatters/
