### PR TITLE
Fix: Old Chalk.JS deprecated method (fixes #5716)

### LINKED ISSUE #5716: v2.5.3 not working with chalk v1.1.2
**What version of ESLint are you using?**
v2.5.3
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
{
  "extends": "name",
  "rules": {
    "no-useless-call": 1,
    "comma-dangle": 2
  }
}

**What did you do? Please include the actual source code causing the issue.**
npm install
**What did you expect to happen?**
working
**What actually happened? Please include the actual, raw output from ESLint.**
.../node_modules/gulp-eslint/node_modules/eslint/lib/formatters/stylish.js:71
                    return chalk.stripColor(str).length;
                                 ^

TypeError: chalk.stripColor is not a function
    at table.stringLength (.../node_modules/gulp-eslint/node_modules/eslint/lib/formatters/stylish.js:71:34)
    at .../node_modules/text-table/index.js:33:21
    at Array.forEach (native)
    at forEach (.../node_modules/text-table/index.js:73:31)
    at .../node_modules/text-table/index.js:32:9
    at Array.reduce (native)
    at reduce (.../node_modules/text-table/index.js:63:30)
    at module.exports (.../node_modules/text-table/index.js:31:17)
    at .../node_modules/gulp-eslint/node_modules/eslint/lib/formatters/stylish.js:46:19
    at Array.forEach (native)

Thank you

### PR DESCRIPTION
**Pull request by morrissinger**

### CODE REVIEW

**Comment by gyandeeps** [comment]
`chalk` fixed it with `1.1.3` version, with that do we still need this change?

**Comment by morrissinger** [comment]
@gyandeeps, that isn't true. look at chalk 1.1.3. you'll see stripColor is not in the project.

**Comment by gyandeeps** [comment]
None of our unit test are failing since the release of `1.1.3`. Am I missing something?

**Comment by morrissinger** [comment]
Ah, you are correct that 1.1.3 fixes this, but that's not what npm is pulling. just did npm install, which pulled from master, which doesn't have the change. so anyone who tries pulling this from npm is going to have a problem, hence this fix.

**Comment by gyandeeps** [comment]
`chalk` master branch has breaking changes because they are about to release a major version.
If we want to do a fix on our end, i think that should be to change the version on `chalk` dependency to `^1.1.3`.

I dont think we need to include another dependency here.

**Comment by morrissinger** [comment]
Suit yourself, @gyandeeps. That would have been an easier fix, but I assumed that pinning eslint to an old version of Chalk would have been undesirable. I can resubmit with the fix you suggested.

**Comment by gyandeeps** [comment]
I am sorry if i was not clear, but I never said hard-version `chalk`, what i said was to use `chalk` : `^1.1.3` (this is not hard-version if we are on the same terms on what "hard-version" means)

**Comment by morrissinger** [comment]
@gyandeeps, now versioned to ^1.1.3.

**Comment by morrissinger** [comment]
This failed because ESLint's build system died on the fact that there is more than one commit in this PR. I am going to close and reopen.
