### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by dennyferra** [eslint/eslint#6159]
**What version of ESLint are you using?**
2.10.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "rules": {
    "react/jsx-no-bind": 0,
    "react/prefer-stateless-function": 0,
    "comma-dangle": 0,
    "no-use-before-define": 0,
    "consistent-return": 0
  },
  "plugins": [
    "react"
  ]
}
```

**What did you do? Please include the actual source code causing the issue.**
Just ran eslint on my project as normal

**What did you expect to happen?**
No parser error

**What actually happened? Please include the actual, raw output from ESLint.**
Get the following error:
TypeError: Cannot read property 'value' of undefined

On linting this file:
```
module.exports = {
  'Home.Company': 'Comapny ABC'
};
```

> Cannot read property 'value' of undefined
> TypeError: Cannot read property 'value' of undefined
>     at isEnclosedInParens (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/eslint/lib/rules/no-return-assign.js:23:21)
>     at EventEmitter.AssignmentExpression (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/eslint/lib/rules/no-return-assign.js:51:32)
>     at emitOne (events.js:95:20)
>     at EventEmitter.emit (events.js:182:7)
>     at NodeEventGenerator.enterNode (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/eslint/lib/util/node-event-generator.js:40:22)
>     at CodePathAnalyzer.enterNode (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
>     at CommentEventGenerator.enterNode (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
>     at Controller.traverser.traverse.enter (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/eslint/lib/eslint.js:886:36)
>     at Controller.__execute (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/estraverse/estraverse.js:397:31)
>     at Controller.traverse (/Users/Shared/Jenkins/Home/workspace/Bulk-Downloader-Test/node_modules/estraverse/estraverse.js:501:28)

This was working on 2.9.0

**Comment by framerate** [comment]
I'm seeing this too this morning. eslint@2.10.0 and eslint@latest both

**Comment by CodyReichert** [comment]
Also see https://github.com/eslint/eslint/issues/6159

**Comment by framerate** [comment]
If I drop to 2.9.0 I get
```
Error: Cannot find module 'estraverse-fb'
```

FYI

**Comment by gyandeeps** [comment]
its because of #6158 .

**Comment by CodyReichert** [comment]
Pinning `eslint@2.9.0` and using `babel-eslint@latest` should be working.

**Comment by meeber** [comment]
This particular issue occurs with the default parser as well. Here's a barebone example:

**ESLint Config:**

```yml
rules:                                                                          
  no-return-assign: 2 
```

**File being linted:**

```js
module.exports = {a: 42};
```

**Error:**

> Cannot read property 'value' of undefined
> TypeError: Cannot read property 'value' of undefined
>     at isEnclosedInParens (/opt/code/eslint-test/node_modules/eslint/lib/rules/no-return-assign.js:23:21)
>     at EventEmitter.AssignmentExpression (/opt/code/eslint-test/node_modules/eslint/lib/rules/no-return-assign.js:51:32)
>     at emitOne (events.js:96:13)
>     at EventEmitter.emit (events.js:188:7)
>     at NodeEventGenerator.enterNode (/opt/code/eslint-test/node_modules/eslint/lib/util/node-event-generator.js:40:22)
>     at CodePathAnalyzer.enterNode (/opt/code/eslint-test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
>     at CommentEventGenerator.enterNode (/opt/code/eslint-test/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
>     at Controller.traverser.traverse.enter (/opt/code/eslint-test/node_modules/eslint/lib/eslint.js:886:36)
>     at Controller.__execute (/opt/code/eslint-test/node_modules/estraverse/estraverse.js:397:31)
>     at Controller.traverse (/opt/code/eslint-test/node_modules/estraverse/estraverse.js:501:28)
> npm ERR! Test failed.  See above for more details.

The error only occurs in `2.10.0` and only when the `no-return-assign` rule is enabled.

**Comment by gyandeeps** [comment]
Guys can u plz try the solution on here #6160

**Comment by meeber** [comment]
@gyandeeps Same error using that build.

A similar-looking error occurs with the new `returnAssign` option in the `no-extra-parens` rule.

This example is also with the default parser. I'm not using babel.

**ESLint Config:**
```yml
rules:                                                                                                                                  
  no-extra-parens:                                                                                                                      
    - error                                                                                                                             
    - all                                                                                                                               
    - returnAssign: false
```

**File being linted:**
```js
function ohno () {                                                                                                                      
  return;                                                                                                                               
}
```

**Error:**
> Cannot read property 'type' of null
> TypeError: Cannot read property 'type' of null
>     at containsAssignment (/opt/code/eslint-test2/node_modules/eslint/lib/rules/no-extra-parens.js:146:21)
>     at isReturnAssignException (/opt/code/eslint-test2/node_modules/eslint/lib/rules/no-extra-parens.js:171:24)
>     at EventEmitter.ReturnStatement (/opt/code/eslint-test2/node_modules/eslint/lib/rules/no-extra-parens.js:589:21)
>     at emitOne (events.js:96:13)
>     at EventEmitter.emit (events.js:188:7)
>     at NodeEventGenerator.enterNode (/opt/code/eslint-test2/node_modules/eslint/lib/util/node-event-generator.js:40:22)
>     at CodePathAnalyzer.enterNode (/opt/code/eslint-test2/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
>     at CommentEventGenerator.enterNode (/opt/code/eslint-test2/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
>     at Controller.traverser.traverse.enter (/opt/code/eslint-test2/node_modules/eslint/lib/eslint.js:886:36)
>     at Controller.__execute (/opt/code/eslint-test2/node_modules/estraverse/estraverse.js:397:31)
> npm ERR! Test failed.  See above for more details.

**Comment by gyandeeps** [comment]
@meeber Can u plz log a separate issue for ur error.

**Comment by gyandeeps** [comment]
@meeber Plz log a separate issue for that rule. thanks
