### ISSUE TITLE
Getting unused vars error when the variable is used in JSX

### ISSUE THREAD

**Issue by veeracs** [eslint/eslint#5291]
Getting following error,
   9:8   error    "favicon" is defined but never used                   no-unused-vars

when my React's render method code is,
```
  render() {
    const favicon = require('../../../favicon.ico');
    return (
      <html>
        <head>
          <meta charSet="utf-8" />
          <link rel="shortcut icon" href={favicon} type="image/x-icon" />
```

**Comment by veeracs** [comment]
here's my eslint config, 
```
{ 
  "parser": "babel-eslint",
  "extends": "eslint-config-airbnb",
    "env": {
    "browser": true,
    "node": true    
  },
  "rules": {
    "react/no-multi-comp": 0,
    "import/default": 0,
    "import/no-duplicates": 0,
    "import/named": 0,
    "import/namespace": 0,
    "import/no-unresolved": 0,
    "import/no-named-as-default": 1,
    "comma-dangle": 0,
    "indent": [2, 2, {"SwitchCase": 1}],
    "no-console": 0,
    "no-alert": 0
  },
  "plugins": [
    "react",
    "import"
  ],
  "settings": {
    "import/parser": "babel-eslint",
    "import/resolve": {
      "moduleDirectory": ["node_modules", "lib"]
    }
  },
  "globals": {
    "__DEVELOPMENT__": true,
    "__CLIENT__": true,
    "__SERVER__": true,
    "__DISABLE_SSR__": true,
    "__DEVTOOLS__": true
  }
}
```

my eslint dependencies,

```
"devDependencies": {
    "babel-core": "6.4.5",
    "babel-eslint": "4.1.8",
    "babel-loader": "6.2.1",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-stage-0": "6.3.13",
    "babel-runtime": "6.3.19",
    "babel-tape-runner": "2.0.0",
    "better-npm-run": "0.0.6",
    "concurrently": "1.0.0",
    "css-loader": "0.23.1",
    "eslint": "1.10.3",
    "eslint-config-airbnb": "4.0.0",
    "eslint-plugin-import": "0.12.1",
    "eslint-plugin-react": "3.16.1",
```

**Comment by nzakas** [comment]
Can you try it with the default parser instead of babel-eslint?

**Comment by veeracs** [comment]
@nzakas will give it try, thanks!

**Comment by veeracs** [comment]
@nzakas 

It actually fixes the issue with  no-unused-vars. But it's giving a different parser issue on several files,
0:0  error  Parsing error: parser.parse is not a function

It could be an issue with babel-eslint or some missing config.

**Comment by zbinlin** [comment]
I reproduced this bug in eslint **2.0**, but not in eslint **1.0**.

**Comment by nzakas** [comment]
@veeracs what do you have `parser` set to in your config? Is it present? If so, just remove it. If you still get an error, please run with `--debug` and share the output.

**Comment by stebunovd** [comment]
I have the same problem after upgrade to 2.1.0, and I was also using babel-eslint as a parser. I tried to switch to default as suggested above, but it didn't helped.

My config (after switch to default parser):
```
{
  "extends": "eslint:recommended",
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "indent": [2, 2, {"SwitchCase": 1, "VariableDeclarator": 2}],
    "max-len": [2, 80, 4],
    "no-alert": 0,
    "quotes": [2, "single"]
  }
}
```

It produces ``2:8  error  'NavLink' is defined but never used  no-unused-vars`` for the following file:

```
import DataStore from '../../stores/DataStore';
import NavLink from '../NavLink';
import React from 'react';
import storeListenerMixin from '../../mixins/storeListenerMixin';


var UsernameChangeDone = React.createClass({
  mixins: [storeListenerMixin(DataStore)],

  getStateFromStores: function() {
    var user = DataStore.currentUser();
    return {
      username: user && user.get('username')
    };
  },

  render: function() {
    return (
      <div className="form-saved" id="username-changed">
        <p>
          Your username has been changed to{' '}
          <span className="value">{this.state.username}</span>
        </p>
        <NavLink route={this.props.routes.HOME} className="cub-btn">
          <i></i>OK
        </NavLink>
      </div>
    );
  }
});


export default UsernameChangeDone;
```

**Comment by ilyavolodin** [comment]
Oh, I think I know what this is. You don't have any rules for `eslint-plugin-react` specified in your config. Before v2 we supported default configuration for plugins (as in, plugins had ability to enable some of their own rules by default, as soon as you said you want to use that plugin). Now that functionality has been removed and replaced with embedded configs. So you need to enable one of the `eslint-plugin-react` rules manually until they can create embedded config. Basically, none of your react plugin rules are enabled now. And marking react variables as used was responsibility of one of those rules (don't remember which one).

**Comment by nzakas** [comment]
@stebunovd this is a different issue that the one originally reported here. @ilyavolodin is correct for your case, because `eslint-plugin-react` needs to modify identifier lookup in JSX tags. The original report is about expressions inside of JSX, which we should support natively.

**Comment by stebunovd** [comment]
ok, thank you for your help!

**Comment by veeracs** [comment]
@nzakas sorry for delayed response, I was revisiting this, and I couldn't seem to reproduce this bug. Here's my test repo, https://github.com/veeracs/isomorphic-tools-seed
Switch to the develop branch. This ticket may be closed, unless someone else is able to reproduce the issue. Thank you for your time on this.

**Comment by nzakas** [comment]
@veeracs ok, let us know if you end up seeing it again.

**Comment by veeracs** [comment]
ok, thanks @nzakas
